version: '2'

volumes:
  ecrLib:

services:
  postgres:
    build: ./postgres/.
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=omop_v5
      - POSTGRES_PASSWORD=i3lworks
      - POSTGRES_DB=omop_v5

  gt-fhir2:
    build: ./gt-fhir2-docker/.
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ecrLib:/ecrLib
    depends_on:
      - postgres
    command: ["/usr/local/bin/wait-for-postgres.sh","postgres","catalina.sh","run"]
